apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 8089
    nodePort: 30001
    targetPort: 8080
    protocol: TCP
  selector:
    app: helloworld-app
  type: NodePort
