apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  revisionHistoryLimit: 100
  selector:
    matchLabels:
      app: helloworld-app
  template: 
    metadata:
      labels:
        app: helloworld-app
    spec:
      containers:
      - name: k8s-demo-go-container
        image: josuegiron/k8s-demo-go:1.0.0
        ports:
        - containerPort: 8080
        env:
         - name: SECRET_USERNAME
           valueFrom: 
             secureKeyRef:
                name: config-toml
                key: username
         - name: SECRET_PASSWORD
           valueFrom: 
             secureKeyRef:
                name: config-toml
                key: password
